import {
  IoHomeOutline,
  IoLayersOutline,
  IoGridOutline,
  IoPersonOutline,
  IoBriefcaseOutline,
  IoPaperPlaneOutline,
  IoLocationOutline,
  IoMoonOutline,
  IoSunnyOutline,
  IoSendOutline,
  IoLogoFacebook,
  IoLogoLinkedin,
  IoLogoGithub,
  IoSparklesOutline,
  IoArrowForwardOutline,
  IoServerOutline,
  IoColorPaletteOutline,
  IoTerminalOutline,
  IoCodeSlashOutline,
  IoPhonePortraitOutline,
  IoGitNetworkOutline,
  IoCloudDoneOutline,
  IoMailOutline,
  IoCallOutline,
  IoMenuOutline,
  IoCloseOutline,
  IoExpandOutline,
  IoFolderOutline,
  IoTimeOutline,
  IoShieldCheckmarkOutline,
  IoBusinessOutline,
  IoSchoolOutline,
  IoCopyOutline,
  IoCheckmarkOutline,
  IoConstructOutline,
  IoCloudOutline,
  IoFileTrayFullOutline,
} from 'react-icons/io5'

// Bundled (build-time) icon set — mirrors the Ionicons v5 names used
// throughout the app, so no runtime/CDN script is needed to render icons.
const ICONS = {
  'home-outline': IoHomeOutline,
  'layers-outline': IoLayersOutline,
  'grid-outline': IoGridOutline,
  'person-outline': IoPersonOutline,
  'briefcase-outline': IoBriefcaseOutline,
  'paper-plane-outline': IoPaperPlaneOutline,
  'location-outline': IoLocationOutline,
  'moon-outline': IoMoonOutline,
  'sunny-outline': IoSunnyOutline,
  'send-outline': IoSendOutline,
  'logo-facebook': IoLogoFacebook,
  'logo-linkedin': IoLogoLinkedin,
  'logo-github': IoLogoGithub,
  'sparkles-outline': IoSparklesOutline,
  'arrow-forward-outline': IoArrowForwardOutline,
  'server-outline': IoServerOutline,
  'color-palette-outline': IoColorPaletteOutline,
  'terminal-outline': IoTerminalOutline,
  'code-slash-outline': IoCodeSlashOutline,
  'phone-portrait-outline': IoPhonePortraitOutline,
  'git-network-outline': IoGitNetworkOutline,
  'cloud-done-outline': IoCloudDoneOutline,
  'mail-outline': IoMailOutline,
  'call-outline': IoCallOutline,
  'menu-outline': IoMenuOutline,
  'close-outline': IoCloseOutline,
  'expand-outline': IoExpandOutline,
  'folder-outline': IoFolderOutline,
  'time-outline': IoTimeOutline,
  'shield-checkmark-outline': IoShieldCheckmarkOutline,
  'business-outline': IoBusinessOutline,
  'school-outline': IoSchoolOutline,
  'copy-outline': IoCopyOutline,
  'checkmark-outline': IoCheckmarkOutline,
  'construct-outline': IoConstructOutline,
  'cloud-outline': IoCloudOutline,
  'file-tray-full-outline': IoFileTrayFullOutline,
}

export default function Icon({ name, className }) {
  const Component = ICONS[name]
  if (!Component) return null
  return <Component className={className} aria-hidden="true" />
}
