import manifest from '../data/imageManifest.json'

// Swap an original image path (e.g. '/images/case 1.png') for its optimized
// WebP copy, generated by `npm run images`. Picks the smallest copy at least
// `width` pixels wide, or the largest there is. Falls back to the original
// if the image hasn't been optimized yet.
export function optimized(src, width = 640) {
  const entry = manifest[src]
  if (!entry) return src
  const sizes = Object.keys(entry.variants)
    .map(Number)
    .sort((a, b) => a - b)
  const pick = sizes.find((w) => w >= width) ?? sizes[sizes.length - 1]
  return entry.variants[pick]
}

// Card-sized copy for thumbnails, and the large copy for the full-screen view
export const thumb = (src) => optimized(src, 640)
export const full = (src) => optimized(src, 1600)
export const photo = (src) => optimized(src, 320)
